//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

package semana06;


import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class GuiTerminalBancario extends JPanel {
    private JButton btDepositar;
    private JButton btSacar;
   
    private JLabel lbTitular;
    private JTextField tfTitular;
    private JTextField tfSaldo;
    private JLabel lbSaldo;
    private JLabel lbValor;
    private JTextField tfValor;
    private ContaBancaria conta;

    public GuiTerminalBancario() {
        //construct components
        btDepositar = new JButton ("Depositar");
        btDepositar.setMnemonic('D');
        btDepositar.setToolTipText("Realiza o depósito");
        btSacar = new JButton ("Sacar");
        btSacar.setMnemonic('S');
        btSacar.setToolTipText("Realiza o saque");
        lbTitular = new JLabel ("Titular:");
        tfTitular = new JTextField (5);
        tfSaldo = new JTextField (5);
        tfSaldo.setEditable(false);
        tfSaldo.setText("0");
        lbSaldo = new JLabel ("Saldo:");
        lbValor = new JLabel ("Valor");
        tfValor = new JTextField (5);
        conta = new ContaBancaria();

        //adjust size and set layout
        setPreferredSize (new Dimension (704, 454));
        setLayout (null);

        //add components
        add (btDepositar);
        add (btSacar);
        
        add (lbTitular);
        add (tfTitular);
        add (tfSaldo);
        add (lbSaldo);
        add (lbValor);
        add (tfValor);

        //set component bounds (only needed by Absolute Positioning)
        btDepositar.setBounds (60, 180, 100, 20);
        btSacar.setBounds (250, 180, 100, 20);
       
        lbTitular.setBounds (10, 30, 100, 25);
        tfTitular.setBounds (85, 30, 275, 25);
        tfSaldo.setBounds (85, 65, 150, 30);
        lbSaldo.setBounds (10, 65, 100, 25);
        lbValor.setBounds (15, 110, 100, 25);
        tfValor.setBounds (85, 110, 150, 30);
        
        btDepositar.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				//JOptionPane.showMessageDialog(btDepositar, "oi");
				conta.depositar(Double.parseDouble(tfValor.getText()));
				atualizarSaldo();
				
				
			}
		});
        
        btSacar.addActionListener(new ActionListener() {
			
     			@Override
     			public void actionPerformed(ActionEvent e) {
     				//JOptionPane.showMessageDialog(btDepositar, "oi");
    				String s = conta.sacar(Double.parseDouble(tfValor.getText()));
    				JOptionPane.showMessageDialog(btSacar, s);
    				atualizarSaldo();
     			
     				
     			}
     		});
    }
    
    public void atualizarSaldo() {
    	
   
    
    tfSaldo.setText(""+conta.consultar());
	tfValor.setText("");
	tfValor.requestFocus();
	
    }
    
    public static void main (String[] args) {
        JFrame frame = new JFrame ("GuiTerminalBancario");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new GuiTerminalBancario());
        frame.pack();
        frame.setVisible (true);
    }
}
